<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agendar consulta' => '',
    'Are you sure you want to delete this item?' => '',
    'Atualizar' => '',
    'Consultas' => '',
    'Contatos' => '',
    'Create Consulta' => 'Criar consulta',
    'Create Contato' => '',
    'Create Endereco' => '',
    'Create Laudo' => '',
    'Create Medico' => '',
    'Create Usuario' => '',
    'Delete' => '',
    'Enderecos' => '',
    'Laudos' => '',
    'Lista das consultas' => '',
    'Medicos' => '',
    'Remove' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Selecione o paciente que deseja ...' => '',
    'Tem certeza que deseja remover esse laudo?' => '',
    'Update' => '',
    'Update Consulta: {name}' => '',
    'Update Contato: {name}' => '',
    'Update Endereco: {name}' => '',
    'Update Laudo: {name}' => '',
    'Update Medico: {name}' => '',
    'Update Usuario: {name}' => '',
    'Upload' => '',
    'Usuarios' => '',
    'Ver' => '',
];
