<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agendar consulta' => '',
    'Are you sure you want to delete this item?' => 'Tem certeza que quer remover esse item',
    'Atualizar' => '',
    'Consultas' => '',
    'Contatos' => '',
    'Create Consulta' => 'Criar consulta',
    'Create Contato' => 'Criar Contato',
    'Create Endereco' => 'Criar Endereco',
    'Create Laudo' => 'Criar Laudo',
    'Create Medico' => 'Criar Medico',
    'Create Usuario' => 'Criar Usuario',
    'Delete' => 'Remover',
    'Enderecos' => '',
    'Laudos' => '',
    'Lista das consultas' => '',
    'Medicos' => '',
    'Remove' => 'Remover',
    'Reset' => 'Resetar',
    'Save' => 'Salvar',
    'Search' => 'Procurar',
    'Selecione o paciente que deseja ...' => '',
    'Tem certeza que deseja remover esse laudo?' => '',
    'Update' => 'Atualizar',
    'Update Consulta: {name}' => 'Atualizar Consulta: {name}',
    'Update Contato: {name}' => 'Atualizar Contato: {name}',
    'Update Endereco: {name}' => 'Atualizar Endereço: {name}',
    'Update Laudo: {name}' => 'Atualizar Laudo: {name}',
    'Update Medico: {name}' => 'Atualizar Medico: {name}',
    'Update Usuario: {name}' => 'Atualizar Usuario: {name}',
    'Upload' => '',
    'Usuarios' => '',
    'Ver' => '',
];
